# Extraction manifest for shared.js (§11 step 2) — line-marker based.
# Each extract: (file, start_marker, end_marker, occurrence=1)
# end_marker=None → single line. Bytes never pass through the LLM.

V_PAIR_STD_1 = ('Verse: Unto Thee have I lifted up mine eyes', 'take pity on us.')
V_PAIR_STD_2 = ('Verse: Have mercy on us,', 'abasement on the proud.')
M_PAIR_STD_1 = ('Verse: We were filled in the morning', 'guide their sons.')
M_PAIR_STD_2 = ('Verse: And let the brightness', 'do Thou guide aright.')

MANIFEST = {
 'daily_vespers_prokeimena': {
  'sun': {'file':'2-2','tone':8,'text':('Prokeimenon: Behold now, bless ye the Lord','servants of the Lord.'),'verse':('Verse: Ye that stand in the house','our God.')},
  'mon': {'file':'2-3','tone':4,'text':('Prokeimenon: The Lord will hearken unto me','cry unto Him.'),'verse':('Verse: When I called upon Thee','hearken unto me.')},
  'tue': {'file':'2-4','tone':1,'text':('Prokeimenon: Thy mercy, O Lord, shall pursue me','days of my life.'),'verse':('Verse: The Lord is my shepherd','made me to dwell.')},
  'wed': {'file':'2-5','tone':5,'text':('Prokeimenon: O God, in Thy name save me','Thou judge me.'),'verse':('Verse: O God, hearken unto my prayer','mouth.')},
  'thu': {'file':'2-6','tone':6,'text':('Prokeimenon: My help cometh from the Lord','and the earth.'),'verse':('Verse: I have lifted up mine eyes to the Mountains','my help.')},
  'fri': {'file':'2-7','tone':7,'text':('Prokeimenon: O God, my helper art Thou','before me.'),'verse':('Verse: Rescue me from mine enemies','redeem me.')},
 },
 'vespers_pair_sites': {   # verify byte-identity across evenings sun-thu
  'sun': ('2-2', 1), 'mon': ('2-3', 1), 'tue': ('2-4', 1), 'wed': ('2-5', 1), 'thu': ('2-6', 1),
 },
 'matins_pair_sites': {    # standard pair: mon,tue,wed,fri; thu = anomaly; sat = departed trio
  'mon': '2-2', 'tue': '2-3', 'wed': '2-4', 'fri': '2-6',
 },
 'departed_fri_eve': {
  'file':'2-7',
  'v1': ('Verse: Blessed are they whom Thou hast chosen', 'REGEX:^Lord\\.?$'),
  'v2': ('Verse: Their souls * shall dwell among good things.', None),
 },
 'departed_sat_matins': {
  'file':'2-7',
  'v1': ('Verse: Blessed are those whom Thou hast chosen', 'REGEX:^О?\\s*Lord\\.?$'),
  'v2': ('Verse: Their souls * shall dwell among good things.', None),
  'v3': ('Verse: Their memorial * is unto generation and generation.', None),
  'search_after': 'On the Aposticha, these Stichera of the departed',
 },
 'daily_liturgy_propers': {
  'mon': {'file':'2-2',
    'prok': (4, ('Prokeimenon, in Tone IV: He maketh His angels spirits','flame of fire.'), ('Verse: Bless the Lord, O my soul','magnified exceedingly.')),
    'all':  (5, ('Alleluia, in Tone V: Praise Him, all ye His angels','hosts.'), [('Verse: For He spake','created.')]),
    'comm': ('Communion Verse: He maketh His angels spirits','of fire.')},
  'tue': {'file':'2-3',
    'prok': (7, ('Prokeimenon, in Tone VII: The righteous man shall be glad','hope in Him.'), ('Verse: Hearken, O God, unto my prayer','supplication unto Thee.')),
    'all':  (4, ('Alleluia, in Tone IV: The righteous man shall flourish','be multiplied.'), [('Verse: They that are planted','blossom forth.')]),
    'comm': ('Communion Verse: In everlasting remembrance','evil tidings.')},
  'wed': {'file':'2-4', 'prok_label': 'the hymn of the Theotokos',
    'prok': (3, ('Prokeimenon, the hymn of the Theotokos, in Tone III: My soul doth','God my Savior.'), ('Verse: For He hath looked upon','call me blessed.')),
    'all':  (8, ('Alleluia, in Tone VIII: Hearken, O daughter','thine ear.'), [('Verse: The rich among the people','thy countenance.')]),
    'comm': ('Communion Verse: I will take the cup','name of the Lord.')},
  'thu': {'file':'2-5',
    'prok': (8, ('Prokeimenon, in Tone VIII: Their sound hath gone forth','ends of the world.'), ('Verse: The heavens declare the glory of God','His hands.')),
    'all':  (1, ('Alleluia, in Tone I: The heavens shall confess Thy wonders','congregation of saints.'), [('Verse: God Who is glorified','of the saints.')]),
    'comm': ('Communion Verse: Their sound hath gone forth','ends of the world.')},
  'fri': {'file':'2-6',
    'prok': (7, ('Prokeimenon, in Tone VII: Exalt ye the Lord our God','He is holy.'), ('Verse: The Lord is King, let the peoples rage.', None)),
    'all':  (4, ('Alleluia, in Tone IV: Remember Thy congregation','the beginning.'), [('Verse: God is our King before the ages','midst of the earth.')]),
    'comm': ('Communion Verse: Thou hast wrought salvation','O God.')},
  'sat': {'file':'2-7',
    'prok': (8, ('Prokeimenon, in Tone VIII: Be glad in the Lord','righteous.'), ('Verse: Blessed are they whose iniquities','covered.')),
    'prok_departed': (6, ('Prokeimenon, in Tone VI: Their souls shall dwell among good things.', None), None),
    'all':  (4, ('Alleluia, in Tone IV: The righteous cried','their tribulations.'),
             [('Verse: Many are the tribulations','out of them all.'),
              ('Verse: Blessed are they whom Thou hast chosen and taken to Thyself, O','generation and generation.')]),
    'comm': ('Communion Verse: Rejoice in the Lord','the upright.'),
    'comm_departed': ('Communion Verse: Blessed are they whom Thou hast chosen','generation and generation.'),
    'comm_departed_rubric': 'Another, for the departed:',
    'prok_departed_rubric': 'And for the Departed, in Tone VI:'},
 },
 'sat_vespers_prok': {'file':'2-1','tone':6,
  'text': ('The Lord is King, * He is clothed with majesty.', None),
  'verses': [('Verse: The Lord is clothed with strength and He hath girt Himself.', None),
             ('Verse: For He established the universe which shall not be shaken.', None),
             ('Verse: Holiness becometh Thy house, O Lord, unto length of days.', None)]},
 'sat_gv_aposticha_verses': {'file':'2-1', 'verses': [
   ('Verse: The Lord is King: He is clothed with majesty. * The Lord is clothed','girt Himself.'),
   ('Verse: For He established the universe * which shall not be shaken.', None),
   ('Verse: Holiness becometh Thy house, * O Lord, unto length of days.', None)]},
 'lv_theotokos_verses': {'file':'2-1', 'verses': [
   ('Verse: I shall commemorate thy name * in every generation and generation.', None),
   ('Verse: Hearken, O daughter, and see, and incline thine ear','father’s house.'),
   ('Verse: The rich among the people * shall entreat thy countenance.', None)]},
 'virgin_rejoice': {'file':'2-1','tone':4,
  'text': ('O Theotokos and Virgin, rejoice','Savior of our souls. (Thrice)'),
  'rubric': ('Note: If it is a regular Sunday Vigil','the Troparion of the feast (Once).')},
 'evlogitaria': {'file':'2-1',
  'heading': ('The Resurrectional Verses (THE EVLOGITARIA)', None),
  'refrain': ('Blessed art Thou, O Lord, * teach me Thy statutes.', None),
  'troparia': [
   ('The assembly of angels was amazed','freed all from Hades.'),
   ('Why mingle ye myrrh','arisen from the tomb.'),
   ('Very early * the myrrh-bearing women','of the Resurrection.'),
   ('The myrrh-bearing women, * with myrrh came','risen from the tomb.')],
  'glory_verse': ('Glory to the Father, and to the Son, and to the Holy Spirit.', None),
  'glory': ('Let us worship the Father','Thou, O Lord.'),
  'both_now_verse': ('Both now and ever, and unto the ages of ages, amen.', None),
  'both_now': ('In bringing forth the Giver of life','and man.'),
  'closing': ('Alleluia, alleluia, alleluia. Glory to Thee, O God. (Thrice).', None)},
 'polyeleos': {'file':'2-1',
  'rubric': ('If a POLYELEOS is appointed, we chant: (Select verses):', None),
  'verses': [
   ('Verse: Praise ye the name of the Lord; O ye servants, praise the Lord.','REGEX:^Alleluia, alleluia, alleluia\\.$'),
   ('Verse: Blessed is the Lord out of Zion','alleluia, alleluia.'),
   ('Verse: O give thanks unto the Lord, for He is good','alleluia, alleluia.'),
   ('Verse: O give thanks unto the God of heaven','alleluia, alleluia.')],
  'prelent_note': ('(On the Sunday of the Prodigal Son','“By the rivers of Babylon ...,”)'),
  'megalynarion_rubric': ('Then, the Megalynarion of the feast is chanted','of the Lord, or the Theotokos.')},
 'praises_ladder': {'file':'2-1', 'verses': [
   ('Verse: To do among them the judgment that is written','all His saints.'),
   ('Verse: Praise ye God in His saints','REGEX:^power\\.$'),
   ('Verse: Praise Him for His mighty acts','of His greatness.'),
   ('Verse: Praise Him with the sound of trumpet','and harp.'),
   ('Verse: Praise Him with timbrel and dance','flute.'),
   ('Verse: Praise Him with tuneful cymbals','praise the Lord.'),
   ('Verse: Arise, O Lord my God, let Thy hands be lifted high','paupers to the end.'),
   ('Verse: I will confess Thee, O Lord, with my whole heart','Thy wonders.')],
  'search_after': 'On the Praises:'},
 'ode8': {'file':'2-1',
  'rubric': ('After the Troparia from the Menaion for ODE VIII, we chant:', None),
  'text': ('Verse: We praise, we bless, we worship the Lord','throughout all ages.')},
 'gregory': {'file':'2-1',
  'title_rubric': ('Then, the hymn of Gregory the Sinaite.', None),
  'source_note': ('(which is chanted every Sunday after the canon)', None),
  'stanzas': [
   ('It is truly meet to glorify Thee','on the third day.'),
   ('With divine songs','REGEX:^Dominion\\.$'),
   ('Whom all mortals hymn','with faith by all.'),
   ('We magnify Thee, the Godhead','Trinity in Unity.'),
   ('I worship God: the beginningless Father','the threefold Unity.'),
   ('Shine forth Thy dazzling lightning','unapproachable glory.'),
   ('With fear let us glorify Christ the Bestower','glorify Him.')]},
 # ladder byte-comparison sites (FINDING documentation; ladder NOT encoded)
 'ladder_compare': [
  ('name-sake', '2-1', ('Verse: For Thy name’s sake','hoped in the Lord.'), '2-2', ('Verse: For Thy name’s sake','hoped in the Lord.')),
  ('with-the-lord', '2-1', ('Verse: For with the Lord there is mercy','all his iniquities.'), '2-2', ('Verse: For with the Lord there is mercy','all his iniquities.')),
  ('morning-watch', '2-1', ('Verse: From the morning watch','hope in the Lord.'), '2-2', ('Verse: From the morning watch','hope in the Lord.')),
  ('shouldest-mark', '2-1', ('Verse: If Thou shouldest mark','there is forgiveness.'), '2-2', ('Verse: If Thou shouldest mark','there is forgiveness.')),
 ],
}
