#!/usr/bin/env node
// tools/build_temple_index.mjs
// ─────────────────────────────────────────────────────────────────────────────
// The temple-dedication index — every encoded Menaion commemoration that could
// be a parish's dedication, derived FROM THE DATA so the picker can never lag
// behind an encoding session (Bill, Sept 19 2026: "part of updating the
// Menaion should be adding to the availability in this list").
//
//   node tools/build_temple_index.mjs          # (re)write src/data/temple_index.js
//   node tools/build_temple_index.mjs --check  # exit 1 if the file is stale
//
// `--check` runs in `npm run gate` and `npm run validate`, so a new month or a
// new troparion fails the build until the index is rebuilt. The generated file
// is committed (the app imports it statically; the picker must list a
// dedication before its month is loaded).
//
// What qualifies: every service in every month file that carries a
// `troparion`, except entries that are not dedications by nature — a
// forefeast, afterfeast, leavetaking/apodosis, or a "Saturday/Sunday before/
// after" — since a temple is dedicated to a saint or a feast, not to a day in
// a feast period. Entries already in the curated TEMPLE_DEDICATIONS (matched
// by dataKey + service index) are skipped so nothing is listed twice.
//
// `type` (lord | theotokos | saint) is a heuristic on the printed name, used
// by the Liturgy's Little Entrance tables; the curated list carries its own
// categories and is authoritative where the two overlap.
// ─────────────────────────────────────────────────────────────────────────────

import { readdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, "..");
const MENAION_DIR = join(ROOT, "src", "data", "menaion");
const OUT = join(ROOT, "src", "data", "temple_index.js");
const CHECK = process.argv.includes("--check");

const MONTH_NAMES = { "01": "January", "02": "February", "03": "March", "04": "April", "05": "May", "06": "June",
  "07": "July", "08": "August", "09": "September", "10": "October", "11": "November", "12": "December" };

const NOT_A_DEDICATION = /^(forefeast|afterfeast|leave-?taking|apodosis|saturday (before|after)|sunday (before|after)|the (saturday|sunday) (before|after))/i;
const typeOf = (name) => {
  if (/theotokos|mother of god|dormition|annunciation|protection|pokrov|entrance of the (most holy )?theotokos/i.test(name)) return "theotokos";
  if (/\bcross\b|transfiguration|nativity of (our lord|christ)|theophany|baptism of (our|the) lord|ascension|meeting of (our|the) lord|presentation of (our|the) lord|circumcision|holy trinity|pentecost/i.test(name)) return "lord";
  return "saint";
};

// The curated list lives in hours-tool.jsx; read its dataKeys by a narrow regex
// so the two never diverge silently.
const curatedSrc = readFileSync(join(ROOT, "src", "components", "hours-tool.jsx"), "utf8");
const curatedBlock = curatedSrc.slice(curatedSrc.indexOf("const TEMPLE_DEDICATIONS = ["), curatedSrc.indexOf("];", curatedSrc.indexOf("const TEMPLE_DEDICATIONS = [")));
const curated = new Set();
for (const m of curatedBlock.matchAll(/dataKey:\s*"(\d\d-\d\d)"(?:[^}]*arrayIndex:\s*(\d+))?/g)) curated.add(m[1] + "#" + (m[2] || "0"));

const rows = [];
// Calendar order, not filename order: months by their MM key.
const loaded = [];
for (const file of readdirSync(MENAION_DIR).filter(f => /^[a-z]+\.js$/.test(f))) {
  const mod = await import(`file://${join(MENAION_DIR, file)}`);
  loaded.push(mod.default || {});
}
loaded.sort((a, b) => (Object.keys(a)[0] || "").localeCompare(Object.keys(b)[0] || ""));
for (const data of loaded) {
  for (const key of Object.keys(data).sort()) {
    const services = Array.isArray(data[key]) ? data[key] : [data[key]];
    services.forEach((e, i) => {
      if (!e || !e.troparion || !e.saint) return;
      if (NOT_A_DEDICATION.test(String(e.saint).trim())) return;
      if (curated.has(key + "#" + i)) return;
      const mm = key.slice(0, 2);
      const label = String(e.saint).replace(/\s+/g, " ").trim();
      rows.push({
        id: "m-" + key + (i ? "-" + i : ""),
        label: label.length > 72 ? label.slice(0, 69).replace(/[\s,;:]+\S*$/, "") + "…" : label,
        fullLabel: label,
        category: "Encoded commemorations · " + (MONTH_NAMES[mm] || mm),
        source: "menaion", dataKey: key, arrayIndex: i, type: typeOf(label),
        hasKontakion: !!(e.kontakion_ode6 || e.kontakion_ode3 || e.kontakion),
      });
    });
  }
}

const body = [
  "// src/data/temple_index.js — GENERATED by tools/build_temple_index.mjs. Do not edit.",
  "// Every encoded Menaion commemoration with a troparion that could be a parish",
  "// dedication, beyond the curated TEMPLE_DEDICATIONS. Rebuild after any",
  "// encoding session: node tools/build_temple_index.mjs (npm run gate checks it).",
  "",
  "export const TEMPLE_INDEX = [",
  ...rows.map(r => "  " + JSON.stringify(r) + ","),
  "];",
  "",
].join("\n");

const current = existsSync(OUT) ? readFileSync(OUT, "utf8") : null;
if (CHECK) {
  if (current === body) { console.log(`temple index: current (${rows.length} entries)`); process.exit(0); }
  console.log(`temple index: STALE — ${rows.length} entries derivable from the data, file ${current ? "differs" : "missing"}. Run: node tools/build_temple_index.mjs`);
  process.exit(1);
}
if (current !== body) { writeFileSync(OUT, body); console.log(`temple index: wrote ${rows.length} entries → src/data/temple_index.js`); }
else console.log(`temple index: unchanged (${rows.length} entries)`);
