// tools/scan_source.mjs
// ─────────────────────────────────────────────────────────────────────────────
// Octoechos V2 per-file encoding protocol, STEP 1 (octoechos_v2_spec.md §10):
// scan a source file's extracted text layer BEFORE any encoding.
//
//   • Codepoint census — every non-ASCII character, with counts and context
//     samples (the §9.10 homoglyph check: 2-2…2-7 are U+041E contaminated).
//   • Digit-zero-as-O pattern ("0 Lord") — invisible to the codepoint check.
//   • Sic CANDIDATES — stray periods/asterisks, doubled/unclosed quotes,
//     mid-sentence capitals, suspicious spacing (§9.12 artifact classes).
//
// Output is a REVIEW FILE for Bill: per the §9.10 ruling, EVERY flagged item
// goes to him before encoding proceeds. This tool never normalizes, never
// corrects, never decides — it only surfaces.
//
// Usage:
//   node tools/scan_source.mjs <extracted-text-file> [--out <review.md>]
//   (default out: <input>.review.md alongside the input)
// ─────────────────────────────────────────────────────────────────────────────

import { readFileSync, writeFileSync } from 'node:fs';

const args = process.argv.slice(2);
if (args.length === 0 || args[0].startsWith('--')) {
  console.error('Usage: node tools/scan_source.mjs <extracted-text-file> [--out <review.md>]');
  process.exit(2);
}
const inPath = args[0];
const outIdx = args.indexOf('--out');
const outPath = outIdx !== -1 ? args[outIdx + 1] : `${inPath}.review.md`;

const text = readFileSync(inPath, 'utf8');
const lines = text.split(/\r?\n/);

const ctx = (line, i, span = 40) => {
  const s = Math.max(0, i - span), e = Math.min(line.length, i + span);
  return `${s > 0 ? '…' : ''}${line.slice(s, e)}${e < line.length ? '…' : ''}`;
};

// ── 1 · codepoint census (non-ASCII) ─────────────────────────────────────────
const census = new Map();   // cp → { ch, count, isLetter, nonLatinLetter, samples[] }
for (let ln = 0; ln < lines.length; ln++) {
  const line = lines[ln];
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    const cp = ch.codePointAt(0);
    if (cp < 128) continue;
    let rec = census.get(cp);
    if (!rec) {
      rec = {
        ch, count: 0,
        isLetter: /\p{L}/u.test(ch),
        nonLatinLetter: /\p{L}/u.test(ch) && !/\p{Script=Latin}/u.test(ch),
        samples: [],
      };
      census.set(cp, rec);
    }
    rec.count++;
    if (rec.samples.length < 3) rec.samples.push(`line ${ln + 1}: "${ctx(line, i, 30)}"`);
  }
}

// ── 2 · digit-zero-as-O ──────────────────────────────────────────────────────
const digitZero = [];
for (let ln = 0; ln < lines.length; ln++) {
  for (const m of lines[ln].matchAll(/(?:^|\s)0(?=\s+[A-Z])|[A-Z][a-z]*\s+0(?=\s|$|[.,;!?])/g)) {
    digitZero.push(`line ${ln + 1}: "${ctx(lines[ln], m.index)}"`);
  }
}

// ── 3 · sic candidates (§9.12 artifact classes; heuristic triage only) ───────
const CANDIDATE_PATTERNS = [
  [/\s\.\s/g,                      'stray spaced period ("It is truly meet . ...")'],
  [/[a-z]\.\s+[a-z]/g,             'period followed by lowercase (mid-phrase stray period?)'],
  [/\w+\.,|\.\.(?!\.)/g,           'period-comma / doubled period ("the departed., the acrostic")'],
  [/\w\*(?=[\s.,;!?]|$)/g,         'word-attached asterisk ("mercy*", "we praise thee*") — pointing markers are space-padded'],
  [/''|``|""|“{2}|”{2}/g,          'doubled quote mark ("\'\'Accept")'],
  [/,\?|\?,|;\./g,                 'punctuation collision ("O Christ,?")'],
  [/\b(?:art|is|are|hath|doth|did|didst)\.\s+[A-Z]/g, 'verb + period + capital ("Wondrous art. Thou")'],
  [/[a-z],?\s+(?:Sick|They|Even)\b/g, 'mid-sentence capital on a known artifact word (§9.12 attested classes)'],
  [/ {2,}/g,                       'doubled space (possible dropped word site)'],
];
const candidates = [];
for (let ln = 0; ln < lines.length; ln++) {
  const line = lines[ln];
  for (const [re, label] of CANDIDATE_PATTERNS) {
    re.lastIndex = 0;
    for (const m of line.matchAll(re)) {
      candidates.push({ label, where: `line ${ln + 1}`, context: ctx(line, m.index) });
      if (candidates.length > 2000) break;   // runaway guard on binary garbage
    }
  }
}

// ── review file ──────────────────────────────────────────────────────────────
const nonLatin = [...census.entries()].filter(([, r]) => r.nonLatinLetter);
const otherNonAscii = [...census.entries()].filter(([, r]) => !r.nonLatinLetter);
const hex = (cp) => 'U+' + cp.toString(16).toUpperCase().padStart(4, '0');

let md = `# Source scan review — ${inPath}\n\n`;
md += `Generated by tools/scan_source.mjs (spec §10 step 1). Per the §9.10 ruling,\n`;
md += `**every item below goes to Bill for review before encoding proceeds.** This\n`;
md += `tool normalizes nothing and decides nothing.\n\n`;
md += `Input: ${lines.length} lines, ${text.length} characters.\n\n`;

md += `## 1 · Non-Latin LETTER codepoints (§9.10 hard-fail class)\n\n`;
if (nonLatin.length === 0) md += `None found — text layer clean at the letter-codepoint level (like 2-1/Theotokia.pdf).\n\n`;
for (const [cp, r] of nonLatin) {
  md += `- **${hex(cp)} "${r.ch}" × ${r.count}** — proposed handling: normalize-at-encode WITH LOG (§2.8), pending review\n`;
  for (const s of r.samples) md += `    - ${s}\n`;
}

md += `\n## 2 · Digit-zero-as-O pattern (§9.10 extension)\n\n`;
if (digitZero.length === 0) md += `None found.\n`;
for (const d of digitZero) md += `- ${d}\n`;

md += `\n## 3 · Other non-ASCII codepoints (punctuation/diacritics — context)\n\n`;
if (otherNonAscii.length === 0) md += `None found.\n`;
for (const [cp, r] of otherNonAscii) {
  md += `- ${hex(cp)} "${r.ch}" × ${r.count}\n`;
}

md += `\n## 4 · Sic candidates (§9.12 classes — heuristic triage, expect noise)\n\n`;
md += `Verbatim storage keeps every confirmed sic; confirmed items land in\n`;
md += `sic_register.js in the same commit as the data (amendment E).\n\n`;
if (candidates.length === 0) md += `None flagged.\n`;
const byLabel = {};
for (const c of candidates) (byLabel[c.label] ??= []).push(c);
for (const [label, cs] of Object.entries(byLabel)) {
  md += `### ${label} — ${cs.length} hit(s)\n\n`;
  for (const c of cs.slice(0, 40)) md += `- ${c.where}: "${c.context}"\n`;
  if (cs.length > 40) md += `- … and ${cs.length - 40} more.\n`;
  md += `\n`;
}

writeFileSync(outPath, md);
console.log(`Scan complete: ${nonLatin.length} non-Latin letter codepoint(s), ${digitZero.length} digit-zero hit(s), ${candidates.length} sic candidate(s).`);
console.log(`Review file for Bill: ${outPath}`);
if (nonLatin.length || digitZero.length) {
  console.log('⚠ Contamination present — encoding may not proceed until each flagged item is reviewed (§9.10 ruling).');
}
